### PR TITLE
style: add header

### PR DESCRIPTION
**Pull request by pallavithakare28**
I have added a navigation bar.

Issue #31

### CODE REVIEW

**Comment by JasonFritsche** [comment]
Can you please resolve the conflicts?

**Comment by pallavithakare28** [comment]
> Can you please resolve the conflicts?

I am new to OSC, can you please guide me?
For resolving conflict, I have to remove the conflict code , Right?

**Comment by JasonFritsche** [comment]
I merged the changes, no worries. Can you please check that everything looks fine in master?

**Comment by pallavithakare28** [comment]
> I merged the changes, no worries. Can you please check that everything looks fine in master?

Yes, I checked. Everything is fine except the cat's images are not getting loaded.

**Pull request merged**
